#!/bin/bash

# Check to see if the first option is either open or close, then a port number
# ie: magic open 3389
#     magic close 3389
#     magic list
#

# Init
myPrefix=cdj-tmp

# Hey, let's check to see what options were given
case $1 in
    list)
	gcloud compute firewall-rules list
	;;
    open)
    	# Check to make sure the port number is between 0-65535, and is a number, not a string
	if [ $# -eq 2 ] && [ $2 -ge 0 ] && [ $2 -le 65535 ]; then
		gcloud compute \
		   firewall-rules create $myPrefix-$2 \
		   --direction=INGRESS \
		   --priority=1000 \
		   --network=default \
		   --action=ALLOW \
		   --rules=tcp:$2 \
		   --source-ranges=0.0.0.0/0
	else
		myErr=1
	fi
	;;
    close)
    	# Check to make sure the port number is between 0-65535, and is a number, not a string
	if [ $# -eq 2 ] && [ $2 -ge 0 ] && [ $2 -le 65535 ]; then
		gcloud compute -q firewall-rules delete $myPrefix-$2 \

	else
		myErr=1
	fi
	;;
    *)
	myErr=1
	;;
esac


# Something didn't add up... so just display syntax with example
if [ $myErr ]; then
	echo 'Usage: magic list | open <port_number> | close <port_number>'
	echo '   $ magic list         <-- list out the current firewall'
	echo '   $ magic open 3389    <-- open  (create) port 3389 for RDP'
	echo '   $ magic open 22      <-- open  (create) port 22 for SSH'
	echo '   $ magic close 3389   <-- close (remove) port 3389'
	echo '   $ magic close 22     <-- close (remove) port 3389'
fi

